const BASE_URL = 'http://localhost:3000'

export const API_ROUTES = {
    LOGIN: `${BASE_URL}/login`,
    GOOGLE_LOGIN: `${BASE_URL}/auth/google`,
    EQUIPOS: `${BASE_URL}/equipos`,
    ASIGNAR_USUARIO: `${BASE_URL}/equipos/asignacion`,
    REPORTE_FALLA: `${BASE_URL}/equipos/reporte/add`,
    OBTENER_REPORTE: `${BASE_URL}/equipos/reporte`,
    RESOLVER_REPORTE: `${BASE_URL}/equipos/reporte/solucion`,
    OBTENER_PRODUCTOS: `${BASE_URL}/productos`,
    CREAR_PRODUCTO: `${BASE_URL}/productos`,
    ACTULIAZAR_PRODUCTO: (codigo) => `${BASE_URL}/productos/${codigo}`,
    ELIMINAR_PRODUCTO: (codigo) => `${BASE_URL}/productos/${codigo}`,
    OBTENER_VENTAS: `${BASE_URL}/ventas`,
    MANTENIMIENTOS_FIND: `${BASE_URL}/equipos/mantenimientos/find`,
    OBTENER_USUARIOS: `${BASE_URL}/usuarios`,
    OBTENER_AREAS: `${BASE_URL}/areas`,
    ACTULIAZAR_USUARIO: (usuario) => `${BASE_URL}/usuarios/${usuario}`,
    CREAR_USUARIO: `${BASE_URL}/usuarios`,
    ELIMINAR_USUARIO: (usuario) => `${BASE_URL}/usuarios/${usuario}`,
    OBTENER_MANTENIMIENTOS: `${BASE_URL}/equipos/reporte`,
    ACTUALIZAR_MANTENIMIENTOS: `${BASE_URL}/equipos/reporte/solucion`,
    OBTENER_PRODUCTO_POR_CODIGO: (codigo) => `${BASE_URL}/producto?codigo=${codigo}`,
    REGISTRAR_VENTA: `${BASE_URL}/ventas`,
}